---

- name: Change hostname to the FQDN which is used when setting RABBITMQ_USE_LONGNAME (clustering)
  hostname:
    name: "{{ ansible_hostname }}{{ rabbitmq_nodename_suffix }}"

- name: Install python-pip and other tools to install python packages/ansible
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - git-core
    - build-essential
    - python-pip
    # build dependencies to install ansible pip package
    - libyaml-dev
    - libssl-dev
    - libffi-dev
    - python-dev

- name: Install boto & ansible to update clustering on the instance
  pip:
    name: '{{ item }}'
    state: latest
  with_items:
    - pip
    - jinja2
    - boto
    - ansible


- name: Clone this role onto remote machine to be executed on boot
  git:
    repo: https://github.com/mediapeers/ansible-role-rabbitmq.git
    dest: /root/roles/mediapeers.rabbitmq
    version: master
    recursive: yes
    depth: 5
    accept_hostkey: yes

- name: Create ansible library dir in root folder
  file:
    path: /root/library
    state: directory

- name: Copy ec2_search module into library dir
  copy:
    src: ec2_search.py
    dest: /root/library/ec2_search.py

- name: Put ansible.cfg into root dir to configure ansible library/role dirs
  copy:
    src: ansible.cfg
    dest: /root/ansible.cfg

- name: Place playbook using this role into /root
  template:
    src: rabbit_bootup.yml.j2
    dest: /root/rabbit_bootup.yml

- name: Add ansible execution to bootup of instance (hooks intance up to cluster)
  lineinfile:
    dest: /etc/rc.local
    insertbefore: 'exit 0'
    line: 'cd /root/ && /usr/local/bin/ansible-playbook rabbit_bootup.yml >> /var/log/rc.local.log 2>&1'

